# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160319_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.99, max_digits=100, null=True),
        ),
    ]
